version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: compile driver
          command: |
            ./build.sh
      - store_artifacts:
          path: nomad-driver-podman
          destination: /dist
