version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: prepare machine
          command: |
            sudo -E ./.circleci/machinesetup.sh
      - run:
          name: compile driver
          command: |
            ./build.sh
      - store_artifacts:
          path: nomad-driver-podman
          destination: nomad-driver-podman
      - run:
          name: test
          command: |
            sudo -E build/bin/gotestsum --junitfile build/test/result.xml -- -timeout=15m .
      - store_test_results:
          path: build/test/
