version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: compile driver
          command: |
            ./build.sh
      - store_artifacts:
          path: nomad-driver-podman
          destination: nomad-driver-podman
      - run:
          name: test
          command: |
            sudo -E build/bin/gotestsum --junitfile build/test/result.xml -- -timeout=15m .
      - store_test_results:
          path: build/test/
