name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.14.5'

    # - name: Lint Deps
    #   run: make lint-deps

    # - name: Lint
    #   run: make check

    - name: Prepare machine
      run: sudo -E PATH=$PATH:$(go env GOPATH)/bin bash -e .github/machinesetup.sh

    - name: Compile driver
      run: ./build.sh

    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: nomad-driver-podman
        path: nomad-driver-podman

    - name: Test
      run: sudo -E PATH=$PATH:$(go env GOPATH)/bin CI=1 build/bin/gotestsum --junitfile build/test/result.xml -- -timeout=15m .
    - name: Archive test result
      uses: actions/upload-artifact@v1
      with:
        name: test-result
        path: build/test/result.xml
