name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.15'

    - name: Lint Deps
      run: make lint-deps

    - name: Lint
      run: make check

    # - name: setup env
    #   run: |
    #     echo "::set-env name=GOPATH::$(go env GOPATH)"
    #     echo "::add-path::$(go env GOPATH)/bin"
    #   shell: bash

    - name: Prepare machine
      run: sudo bash -e .github/machinesetup.sh

    - name: sanity check
      run: which go

    - name: Compile driver
      shell: bash
      run: ./build.sh

    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: nomad-driver-podman
        path: nomad-driver-podman

    - name: Test
      run: sudo env "PATH=$PATH" CI=1 build/bin/gotestsum --junitfile build/test/result.xml -- -timeout=15m .
    - name: Archive test result
      uses: actions/upload-artifact@v1
      with:
        name: test-result
        path: build/test/result.xml
