name: Run CI Tests

on:
  pull_request:
    paths-ignore:
      - 'build/**'
      - 'examples/**'
      - 'scripts/**'
      - 'CHANGELOG.md'
      - 'README.md'
      - 'Vagrantfile'
  push:
    branches:
      - main
    paths-ignore:
      - 'build/**'
      - 'examples/**'
      - 'scripts/**'
      - 'CHANGELOG.md'
      - 'README.md'
      - 'Vagrantfile'

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
    - uses: hashicorp/setup-golang@v1
    - name: Machine Setup
      run: sudo .github/machinesetup.sh
    - name: Make Setup
      run: |
        make deps
        make check
        make dev
    - name: Make test
      run: sudo -E env "PATH=$PATH" make test-ci
